# This file is generated automatically by : python menuconfig.py -s /home/penn_wang/mpy_prj/MicroPython-dev/ports/ameba-rtos-m/prj.conf
CONFIG_SHELL=n
CONFIG_SUPPORT_ATCMD=n
CONFIG_ATCMD_NETWORK=n
CONFIG_DIAGNOSE_EN_MENU=y
