# Kconfig overrides for EV8711FLM (RTL8711FLM / AmebaGreen2)
CONFIG_SHELL=n
CONFIG_SUPPORT_ATCMD=n
CONFIG_ATCMD_NETWORK=n
CONFIG_DIAGNOSE_EN_MENU=y
CONFIG_STANDARD_TICKLESS=y
CONFIG_ETHERNET=y
CONFIG_MAC_OUTPUT_25M=y
