{ MP_ROM_QSTR(MP_QSTR_WLAN),   MP_ROM_PTR(&wlan_if_type) },
{ MP_ROM_QSTR(MP_QSTR_STA_IF), MP_ROM_INT(MOD_NETWORK_STA_IF) },
{ MP_ROM_QSTR(MP_QSTR_AP_IF),  MP_ROM_INT(MOD_NETWORK_AP_IF) },
#if MICROPY_PY_NETWORK_LAN
{ MP_ROM_QSTR(MP_QSTR_LAN),    MP_ROM_PTR(&network_lan_type) },
#endif
